apiVersion: apps/v1
kind: Deployment
metadata:
  name: simlingo-llm-agent
  labels:
    app: simlingo-llm-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simlingo-llm-agent
  template:
    metadata:
      labels:
        app: simlingo-llm-agent
    spec:
      containers:
        - name: simlingo-llm-agent
          image: simlingo-llm-agent:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9012
              name: http
          env:
            - name: NATS_SERVER_URL
              value: nats://nats:4222
            # Phase 1: Prefix 阶段输入与输出
            - name: LLM_PREFIX_IN_SUBJECT
              value: workflow.simlingo.llm_prefix_input
            - name: LLM_PREFIX_IN_DURABLE
              value: workflow-simlingo-llm-prefix-input
            - name: LLM_PREFIX_OUT_SUBJECT
              value: workflow.simlingo.llm_prefix_output
            # Phase 2: Final 阶段输入与输出
            - name: LLM_FINAL_IN_SUBJECT
              value: workflow.simlingo.llm_final_input
            - name: LLM_FINAL_IN_DURABLE
              value: workflow-simlingo-llm-final-input
            - name: LLM_FINAL_OUT_SUBJECT
              value: workflow.simlingo.llm_output
---
apiVersion: v1
kind: Service
metadata:
  name: simlingo-llm-service
spec:
  selector:
    app: simlingo-llm-agent
  ports:
    - name: http
      protocol: TCP
      port: 9012
      nodePort: 30012
      targetPort: 9012
  type: NodePort