eval:
  agent: simlingo
  checkpoint: /data/gaoshuo/models/2026_01_29_21_59_03_adaption_train_seed_9876/checkpoints/epoch=002.ckpt/pytorch_model.bin
  benchmark: bench2drive
  route_path: /data/gaoshuo/SimLingo-docker-agent/leaderboard/data/bench2drive_split
  seeds: [3]
  tries: 0
  out_root: /data/gaoshuo/SimLingo-docker-agent/eval_results/split_agents_local/latency_comparison
  carla_root: /data/gaoshuo/data/carla0915
  repo_root: /data/gaoshuo/SimLingo-docker-agent
  agent_file: /data/gaoshuo/SimLingo-docker-agent/team_code_adaption/agent_simlingo_remote.py
  team_code: team_code_adaption
  agent_config: not_used
  save_scene_frames: true
  save_scene_raw_frames: false
  scene_frame_stride: 5
  scene_frame_format: png
  token_prune:
    prune_ratio: 0.0
  predict_language:
    enabled: true
    max_new_tokens: 100

budget:
  mode: fixed # random # fixed # rule_based
  fixed_budget: 0.5
  rule_based:
    k_warmup: 5
    eta: 0.03
    safe_threshold: 0.33
    safe_count_threshold: 2
    decay_step: 0.1
    base_offset: 0.25
    base_scale: 0.75
    inst_offset: 0.5
    inst_scale: 0.5
    weights:
      base_mean:
        novelty: 0.29
        speed_shift: 0.25
        route_shift: 0.19
      base_max:
        novelty: 0.09
        speed_shift: 0.11
        route_shift: 0.08
      inst:
        novelty: 0.42
        speed_shift: 0.33
        route_shift: 0.25
    normalization:
      novelty:
        q10: 0.0001102686
        q90: 0.0131252408
      speed_shift:
        q10: 0.0030981766
        q90: 0.7412269711
      route_shift:
        q10: 0.1959435195
        q90: 0.7455124855
